### ISSUE TITLE
Support for ubuntu 18.04

### ISSUE THREAD

**Issue by alexivkin** [arsenetar/dupeguru#519]
Running dupeguru xenial distribution on 18.04 bionic beaver results in ModuleNotFoundError: No module named 'core.pe._block'

The fix is to relink proper libraries - 
```
sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-36m-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/core/pe/_block.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-36m-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-36m-x86_64-linux-gnu.so
```

Could you add this fix the distribution for 18.04 bionic beaver?

**Comment by liwenyip** [comment]
I can confirm this fixes the issue.

**Comment by davestlyon** [comment]
For picture edition, slightly different:

`sudo ln /usr/share/dupeguru_pe/core_pe/_cache.cpython-35m-x86_64-linux-gnu.so  /usr/share/dupeguru_pe/core_pe/_cache.cpython-36m-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru_pe/core_pe/_block.cpython-35m-x86_64-linux-gnu.so  /usr/share/dupeguru_pe/core_pe/_block.cpython-36m-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru_pe/qt/pe/_block_qt.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru_pe/qt/pe/_block_qt.cpython-36m-x86_64-linux-gnu.so`

**Comment by supertin** [comment]
For future me (and possibly others arriving via web searches):
Get python version with "python3 --version".
In the OP's 3 sudo ln commands, change "36m" (near the end of each line) to "3<x>m", where <x> is the middle number from the python version (eg 3.7.3 is 37m).

**Comment by misieck** [comment]
Problem still in 19.04 =(
Fix still works, thanks to supertins foresight.

**Comment by Baltix** [comment]
I've found correctly working DupeGuru 4.0.4 packages at https://launchpad.net/~dupeguru/+archive/ubuntu/ppa 
Thanks @eugenesan :)
See issue #484 (dupeGuru PPA is outdated) for more info.

**Comment by bizmate** [comment]
thanks @Baltix for pointing this out, this fixes the installation problems for me on bionic and should be on the page of https://launchpad.net/~hsoft/+archive/ubuntu/ppa or a redirect for bionic and xenial1

**Comment by arsenetar** [comment]
Duplicate of #484 so I am going to close this one.

**Comment by thomasoliveira** [comment]
For those arriving via web searches looking for support for Ubuntu 20.04:
[https://github.com/arsenetar/dupeguru/pull/665](url)

**Comment by trailing-edge** [comment]
How to get dupeGuru 4.0.3 WORKING on Ubuntu 20.04 !

OS: Ubuntu 20.04.1 LTS
Kernel:  5.4.0-54-generic
Python: 3.8.5
QT: 5.12.8

The posts above did not get dupeguru working  for me on Ubuntu 20.04, but helped me figure out a solution...
Full solution posted for clarity, but draws on the earlier work of others :)

NOTE: dupeguru 4.0.4 installs, but FAILS to run on my system
Error: AttributeError: 'QTabWidget' object has no attribute 'setTabVisible'
Apparent cause: dupeguru 4.0.4 requires QT 5.15 as setTabVisible added in QT version 5.15 (and I didn't want to go there...)

How to successfully install dupeguru 4.0.3 on Ubuntu 20.04:

a) Download and install dupeguru_4.0.3~xenial_amd64.deb package from here: https://launchpad.net/~hsoft/+archive/ubuntu/ppa/+files/dupeguru_4.0.3~xenial_amd64.deb
If you run dupeguru now, you will get the infamous ModuleNotFoundError: No module named 'core.pe._block' error. We will now fix that..

b) Identify your current version of python:
$ python3 --version
$ Python 3.8.5 (Major.Minor.Patch)

We need Major and Minor from your python 3 version (eg MM=38 in example above)

c) Create new links to existing libraries in /usr/share/dupeguru/core/pe and /usr/share/dupeguru/qt/pe:
Replace MM string in link commands below with the value of MM determined in step above (eg 38)
NOTE! it is 38 NOT 38m (or 36m etc ) as some have suggested/had work for them!

sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-MM-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/core/pe/_block.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-MM-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-MM-x86_64-linux-gnu.so

eg in  my case:
sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-38-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/core/pe/_block.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-38-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-38-x86_64-linux-gnu.so

Hope this saves others spending time figuring out a fix!

**Comment by glubsy** [comment]
> NOTE: dupeguru 4.0.4 installs, but FAILS to run on my system
> Error: AttributeError: 'QTabWidget' object has no attribute 'setTabVisible'

That's odd. Are you sure you are talking about 4.0.4RC from the releases? It sounds like you're talking about the latest git commits instead. 
I don't think 4.0.4 ever used QTabWidgets, as this was only introduced in the current master branch (and it will be broken until the commits fixing that bug are merged in)

**Comment by trailing-edge** [comment]
Hmm, good point... Unfortunately, after getting dupeguru 4.0.3 working, I cleaned up much of the mess of source and packages I had lying around, but I did keep "dupeguru_4.0.4-1_amd64.deb" so I'm guessing that's what I had problems with - coz I usually start with the path of least resistance ie with packages - lol

**Comment by aa755** [comment]
today, I was getting the same error on arch linux. `yay -S dupeguru` (reinstall the package) solved it.

**Comment by harmtemolder** [comment]
`yay -S dupeguru` did not solve it for me (on Manjaro). This did:

```shell
sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-39-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-310-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/core/pe/_block.cpython-39-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-310-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-39-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-310-x86_64-linux-gnu.so
```

**Comment by UtopianElectronics** [comment]
@harmtemolder 

This doesn't work for me on Fedora 37. Those three commands give the error that the "file exists".

**Comment by v3DJG6GL** [comment]
For those still/again affected from that issue:
You have to adjust the command depending on your installed python version:
If e.g
`python3 --version` outputs `Python 3.12.7`, you must adjust the above mentioned command as follows:
```
sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-39-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-312-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/core/pe/_block.cpython-39-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-312-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-39-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-312-x86_64-linux-gnu.so
```
---> Replacing `310` (python version `3.10`) with `312` (python version `3.12`)
