### ISSUE TITLE
 Impossible to install any dupeguru releases in ubuntu 18.04

### ISSUE THREAD

**Issue by Phlique** [arsenetar/dupeguru#1048]
I've always liked your program very much.
But at the present time, I had the misfortune to uninstall the version 'dupeguru v. 4.1.1-0' installed in  my Ubuntu 18.04 bionic system (which I should never have done!), in order to upgrade to the current recommended version '4.3.1-1'.
To proceed with this reinstall of 4.3.1-1 currently in the sources, I have first installed all the required dependencies (https://github.com/arsenetar/dupeguru), starting with the required dependencies :
Prerequisites:
    - Python 3.7+ 
    - PyQt5 
And in addition: python3-pyqt5, pyqt5-dev-tools (on some systems, see note), python3-venv (only if using a virtual environment), python3-dev build-essential 

After 2 days of trying to install this last update, it failed!

I tried everything, in particular, installing older versions (releases), retrieved from :https://github.com/arsenetar/dupeguru/releases, from 4.03 onwards to most recent: all of them failed, ex. dupeguru_4.1.1-0 eugenesan~bionic1 (some of them (ex. 4.1.1, 4.2.0, ), when installed and running, crashes). 
I consulted a lot of sites on "how to install dupeguru" and on python pyqt5, in vain. Impossible for me to reinstall any dupeguru releases on ubuntu 18.04 (my 18.04 bionic distribution is perfectly clean (lynis), I finally had doubts!)
I thought I had despaired for real when I realize that I had the chance to install this same 'dupeguru v. 4.1.1-0' on another machine I own: a laptop PC (still with Ubuntu 18.04), I was able to recover the 'deb' thanks to the saving command 'dpkg-repack (put an unpacked .deb file back together). And this time it worked! I could finally get back, thanks to this stratagem, a working dupeguru ('saved by the bell').
Nevertheless, I felt a big frustration, a serious stress. How is it possible that you can't reinstall any version of dupeguru on ubuntu 18.04 with the packages currently provided, all the others having disappeared, especially 'dupeguru v. 4.1.1-0', totally unavailable. https://launchpad.net/~dupeguru/+archive/ubuntu/ppa/+packages ?
Does it mean that dupeguru 4.3.1-1 is only uninstallable with Ubuntu 20.04 or higher installed?
If I didn't have a 'dupeguru v. 4.1.1-0' installed somewhere, I'd have gone ‘chou blanc’! This saved me (from the blues).
Could it be from the python installation and links pointing to the newly installed version? I don't master well python and its multiple versions!

- OS: Ubuntu 18.04 
 - Version [e.g. 4.1.1-0]
 
Attached Documents:

[Copie - pope@pope-MS-7B53: _Téléchargements_dupeguru_4.3.1-1~ppa~bionic1_dupeguru-4.3.1$ make && make run.txt](https://github.com/arsenetar/dupeguru/files/9647198/Copie.-.pope%40pope-MS-7B53._Telechargements_dupeguru_4.3.1-1.ppa.bionic1_dupeguru-4.3.1.make.make.run.txt)
[Copie - Summary - install and check of 'pip3 install --user pyqt5' à l'attention de Arsenetar.txt](https://github.com/arsenetar/dupeguru/files/9647199/Copie.-.Summary.-.install.and.check.of.pip3.install.--user.pyqt5.a.l.attention.de.Arsenetar.txt)

Installation test: 4.2.0 A problem occurred 
Application name:dupeGuru
Version: 4.2.0 install
Python: 3.6.9
Operating System: Linux-4.15.0-193-generic-x86_64-with-Ubuntu-18.04-bionic
Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/tabbed_window.py", line 224, in changeEvent
    if event.type() == QEvent.Type.WindowStateChange and not self.isMaximized():
AttributeError: type object 'Type' has no attribute 'WindowStateChange'

[pope@pope-MS-7B53: _Téléchargements_dupeguru_4.1.1-0 eugenesan~bionic1_dupeguru-4.1.1$ make.txt](https://github.com/arsenetar/dupeguru/files/9647200/pope%40pope-MS-7B53._Telechargements_dupeguru_4.1.1-0.eugenesan.bionic1_dupeguru-4.1.1.make.txt)

**Comment by glubsy** [comment]
Thanks for reporting. 

A fix for the `'Type' has no attribute 'WindowStateChange'` crash shown in the screenshot here was introduced by https://github.com/arsenetar/dupeguru/pull/980
If you use the latest version or compile from source you shouldn't have any issue as long as your pyqt5 is also the latest version.

As for the compilation failure, it seems you might be missing python's setuptools maybe? 

What is the error you get by running the latest packaged version (4.3.1)?

**Comment by Phlique** [comment]
Thanks very much

- I've already looked at the fix for the 'Type' has no attribute 'WindowStateChange' crash
 
- python's setuptools is installed on my system

- The error I get by running the latest packaged version (4.3.1) is:
pope@pope-MS-7B53: /Téléchargements/dupeguru_4.3.1-1 ppa bionic1/dupeguru-4.3.1$ make && make run
dh_prep
dh_installdirs
touch build_pe_modules.py
python3 build_pe_modules.py
Traceback (most recent call last):
  File "build_pe_modules.py", line 7, in <module>
    from setuptools import setup, Extension
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/usr/local/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
pope@pope-MS-7B53: /Téléchargements/dupeguru_4.3.1-1 ppa bionic1/dupeguru-4.3.1$ 

Exactly the same as 'master'.

I don't know how to apply the fix (qt/tabbed_window.py) proposed in :

Apply @arsenetar's proposed change to fix for errors on window change event. Solves #937. #980 
https://github.com/arsenetar/dupeguru/pull/980/commits/32855f6f5459932ccf934eace026d98e3eb3367c

I'am not a developper

nb. the last working installation of dupeguru_4.1.1-0-ppa-bionic1_amd64.deb on Ubuntu 18.04 was in june 2021

![DupeGuru install Logiciels Ubuntu - Source : dupeguru_4 1 1-0-ppa-bionic1_amd64 deb 2021-06-22 17-21-01](https://user-images.githubusercontent.com/114379076/192465566-d343fddc-9a82-465d-b598-4a394aeee200.png)

Nb. 'tilde' replaced by space otherwise line crossed out

**Comment by arsenetar** [comment]
@Phlique that error would lead me to believe there is something wrong with your python 3.8 installation.  I can build and run the current version of dupeGuru from the `master` branch using python 3.7 in Ubuntu 18.04.  Unrelated to your issue but I made sure my python environment had latest `setuptools` and `pip`, and had to install `pyqt5` via `pip` since an apt package is not available for python 3.7.

**Comment by arsenetar** [comment]
@Phlique To answer some of your prior comments:
- The screenshot in your original message shows python 3.6.9 which is an unsupported python version
- Since you are using an older Ubuntu version system packages for newer python3 versions are under python 3.x such as python 3.7 or python3.8
- Can't comment much without actual errors on the other versions of the dupuGuru not working for you, versions 4.1.0 and up require python versions specified in the release notes for the deb archives which starts at python 3.7.
- The older versions are still provided in the PPA, the ppa page filters older `superseeded` packages see https://launchpad.net/~dupeguru/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=&field.series_filter=bionic  any further issue with the ppa should be directed at @eugenesan.

**Comment by Phlique** [comment]
Thanks, dear Andrew Senetar,
→ that error would lead me to believe there is something wrong with your python 3.8 installation:
I agree but I don't know how to fix it
- The older versions are still provided in the PPA: 	No,
Cf. Package file: No files published for this package. (for all except  'dupeguru - 4.3.1-1~ppa~bionic1')
https://launchpad.net/~dupeguru/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=&field.series_filter=bionic 
-> What I can't understand is that once the dependencies are installed, the installation should be very easy, but it is obviously not!
→ I get confused with python : the checks give me contradictory information :
pope@pope-MS-7B53:~$ pip3 list # for python 3
Package    Version
---------- -------
pip        22.0.4
PyQt5      5.15.7
PyQt5-Qt5  5.15.2
PyQt5-sip  12.11.0
setuptools 56.0.0

Synaptic give :
- python3-pip
version installée :
pip9.0.1-2.3~ubuntu1.18.04.5
- python3-setuptools
Python3 Distutils Enhancements
dernière version disponible :
39.0.1-2	1319 kB

It seems to me that I have installed the necessary updates of python3 correctly. : 
pip        22.0.4 and PyQt5      5.15.7
I definitely don't understand much about python3 and its paths!

**Comment by Phlique** [comment]
→ I safely make python 3.8 as the default version linux (switch) according to:
https://www.jbnet.fr/systeme/linux/linux-changer-la-version-utilisee-par-defaut-de-python-sur-ubuntu-18-04-lts.html and others

→ pope@pope-MS-7B53:'tilde'$ sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 2
[sudo] Mot de passe de pope : 
update-alternatives: utilisation de « /usr/bin/python3.8 » pour fournir « /usr/bin/python » (python) en mode automatique
pope@pope-MS-7B53:~'dollar' sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1


pope@pope-MS-7B53:~$ sudo update-alternatives --config python
Il existe 2 choix pour l'alternative python (qui fournit /usr/bin/python).

  Sélection   Chemin              Priorité  État

* 0            /usr/bin/python3.8   2         mode automatique
  1            /usr/bin/python2.7   1         mode manuel
  2            /usr/bin/python3.8   2         mode manuel

Appuyez sur <Entrée> pour conserver la valeur par défaut[*] ou choisissez le numéro sélectionné :

pope@pope-MS-7B53:~$ sudo update-alternatives --config python

Il existe 2 choix pour l'alternative python (qui fournit /usr/bin/python).

  Sélection   Chemin              Priorité  État

* 0            /usr/bin/python3.8   2         mode automatique
  1            /usr/bin/python2.7   1         mode manuel
  2            /usr/bin/python3.8   2         mode manuel

Entrée choisi 2
Appuyez sur <Entrée> pour conserver la valeur par défaut[*] ou choisissez le numéro sélectionné :
pope@pope-MS-7B53:~$ 

→ This will ensure you have the version of python in use that you intend, everywhere. 
Results:
pope@pope-MS-7B53:~$ python3 -VV
Python 3.8.14 (default, Sep 21 2022, 16:43:15) 
[GCC 7.5.0]
pope@pope-MS-7B53:'tilde'$

pope@pope-MS-7B53:~$ python3 --version
Python 3.8.14
pope@pope-MS-7B53: $

pope@pope-MS-7B53: $ ls -ls /usr/bin/python*
   0 lrwxrwxrwx 1 root root      24 sept. 28 08:37 /usr/bin/python -> /etc/alternatives/python
   0 lrwxrwxrwx 1 root root       9 avril 16  2018 /usr/bin/python2 -> python2.7
3540 -rwxr-xr-x 1 root root 3624880 juil.  1 17:56 /usr/bin/python2.7
   0 lrwxrwxrwx 1 root root      33 juil.  1 17:56 /usr/bin/python2.7-config -> x86_64-linux-gnu-python2.7-config
   0 lrwxrwxrwx 1 root root      16 avril 16  2018 /usr/bin/python2-config -> python2.7-config
   0 lrwxrwxrwx 1 root root       9 oct.  25  2018 /usr/bin/python3 -> python3.6
4428 -rwxr-xr-x 2 root root 4530520 juin  29 13:45 /usr/bin/python3.6
   0 lrwxrwxrwx 1 root root      33 juin  29 13:45 /usr/bin/python3.6-config -> x86_64-linux-gnu-python3.6-config
4428 -rwxr-xr-x 2 root root 4530520 juin  29 13:45 /usr/bin/python3.6m
   0 lrwxrwxrwx 1 root root      34 juin  29 13:45 /usr/bin/python3.6m-config -> x86_64-linux-gnu-python3.6m-config
5004 -rwxr-xr-x 1 root root 5120912 sept.  8 02:02 /usr/bin/python3.8
   0 lrwxrwxrwx 1 root root      16 oct.  25  2018 /usr/bin/python3-config -> python3.6-config
   0 lrwxrwxrwx 1 root root      10 oct.  25  2018 /usr/bin/python3m -> python3.6m
   0 lrwxrwxrwx 1 root root      17 oct.  25  2018 /usr/bin/python3m-config -> python3.6m-config
   0 lrwxrwxrwx 1 root root      16 avril 16  2018 /usr/bin/python-config -> python2.7-config
pope@pope-MS-7B53:
pope@pope-MS-7B53:  pip --version
pip 22.2.2 from /home/pope/.local/lib/python3.8/site-packages/pip (python 3.8)
pope@pope-MS-7B53: $
pope@pope-MS-7B53: $ pip list
Package    Version
---------- -------
pip        22.2.2
PyQt5      5.15.7
PyQt5-Qt5  5.15.2
PyQt5-sip  12.11.0
setuptools 65.4.0
wheel      0.37.1
pope@pope-MS-7B53:  $
pope@pope-MS-7B53:  $ pip3 -V
pip 22.2.2 from /home/pope/.local/lib/python3.8/site-packages/pip (python 3.8)
pope@pope-MS-7B53: $

Everything seems to be OK. And yet, the update is still not done!
Maybe I should upgrade to 20.04 for which python8 is native. This is all I have left to hope for, without absolute certainty.

Issue related to #1001, #975, #637

Nb. 'tilde' replaced by space otherwise line crossed out

**Comment by Phlique** [comment]
For my part, after multiple tests reported above, there is no way to install dupeguru (if it was not pre-installed before, which was still possible in June 2021) on Ubuntu 18. 04 (even dupeguru_4.1.1-0'tilde'eugenesan~bionic1.tar.xz (907.7 KiB, (make: *** [all] Error 1....) is uninstallable), because 18.04 is too old, it seems! Let's hope that with 20.04, it will be ok...

**Comment by Phlique** [comment]
‌
Hello, M. Senetar

On my Linux machine with Ubuntu 18.04 properly installed and after multiple tries reported in ticket #1048, I found no way to install dupeguru with my distribution (dupeguru not installed before). It was still possible to install dupeguru easily in June 2021 (.deb or sources). Currently, the only remaining version that can be installed under bionic 'dupeguru_4.1.1-0 'tilde'eugenesan~bionic1.tar.xz' (907.7 KiB), fails to install (make: *** [all] Error 1....). Is it because 18.04 is too old according to you? However, 18.04 has been extended for another 5 years. Hopefully, with 20.04, I will get satisfaction.

Kind regards.

De : "Andrew Senetar"
A : "arsenetar/dupeguru" ,"Phlique" ,"Mention"
Envoyé: mardi 27 Septembre 2022 10:10
Objet : Re: [arsenetar/dupeguru] Impossible to install any dupeguru releases in ubuntu 18.04 (Issue #1048)
 
@Phlique that error would lead me to believe there is something wrong with your python 3.8 installation. I can build and run the current version of dupeGuru from the master branch using python 3.7 in Ubuntu 18.04. Unrelated to your issue but I made sure my python environment had latest setuptools and pip, and had to install pyqt5 via pip since an apt package is not available for python 3.7.
