### ISSUE TITLE
AttributeError: type object 'Type' has no attribute 'WindowStateChange'

### ISSUE THREAD

**Issue by chchia** [arsenetar/dupeguru#937]
**Describe the bug**
https://github.com/arsenetar/dupeguru/commit/b0baa5bfd677f46f44ea7a25a66fa42de7f49e84#commitcomment-55569628

**To Reproduce**
Compiled under ZorinOS and facing this error, revert to previous commit do not have any problem.

**Desktop (please complete the following information):**
Zorin OS 15.3 (GNU/Linux 5.4.0-81-generic x86_64)

```Traceback (most recent call last):
  File "/home/chchia/dupeguru/qtlib/error_report_dialog.py", line 94, in my_excepthook
    dialog.exec_()
SystemError: <built-in method exec_ of ErrorReportDialog object at 0x7f73b8b16dc8> returned a result with an error set

Original exception was:
Traceback (most recent call last):
  File "/home/chchia/dupeguru/qt/tabbed_window.py", line 224, in changeEvent
    if event.type() == QEvent.Type.WindowStateChange and not self.isMaximized():
AttributeError: type object 'Type' has no attribute 'WindowStateChange'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/chchia/dupeguru/qt/tabbed_window.py", line 224, in changeEvent
    if event.type() == QEvent.Type.WindowStateChange and not self.isMaximized():
AttributeError: type object 'Type' has no attribute 'WindowStateChange'
```

**Comment by arsenetar** [comment]
Not seeing this issue in Debian Qt/PyQt 5.11, Ubuntu 20.04.2 PyQt 5.14.1, and Windows 10 with PyQt 5.15.4.  I'm not sure what packages Zorin OS uses, I would expect this enumeration value to exist regardless as I see nothing in Qt's documentation suggesting otherwise.

**Comment by arsenetar** [comment]
You could try changing the comparison at https://github.com/arsenetar/dupeguru/blob/b0baa5bfd677f46f44ea7a25a66fa42de7f49e84/qt/tabbed_window.py#L224 to use `QEvent.WindowStateChange` instead of `QEvent.Type.WindowStateChange`.  Both forms seem to work for the platforms I have tested.

**Comment by chchia** [comment]
sorry being many question, i tried to build in Ubuntu 20.04, and i got this:

![image](https://user-images.githubusercontent.com/1291771/131216135-25160f35-3502-4f3f-ac80-d3ccf415ca92.png)

```$ python build.py
Building dupeGuru with UI qt
Building dupeGuru
Building PE Modules
running build_ext
copying build/lib.linux-x86_64-3.8/core/pe/_block.cpython-38-x86_64-linux-gnu.so -> core/pe
copying build/lib.linux-x86_64-3.8/core/pe/_cache.cpython-38-x86_64-linux-gnu.so -> core/pe
copying build/lib.linux-x86_64-3.8/qt/pe/_block_qt.cpython-38-x86_64-linux-gnu.so -> qt/pe
Building localizations
Building Qt stuff
pyrcc5 qt/dg.qrc > qt/dg_rc.py
Generating Help
Running Sphinx v4.1.2
loading translations [en]... done
loading pickled environment... done
[autosummary] generating autosummary for: changelog.rst, contribute.rst, developer/core/app.rst, developer/core/directories.rst, developer/core/engine.rst, developer/core/fs.rst, developer/core/gui/deletion_options.rst, developer/core/gui/index.rst, developer/core/index.rst, developer/core/results.rst, ..., developer/hscommon/util.rst, developer/index.rst, faq.rst, folders.rst, index.rst, preferences.rst, quick_start.rst, reprioritize.rst, results.rst, scan.rst
Failed to import 'hscommon.jobprogress.qt': no module named hscommon.jobprogress.qt
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 2 changed, 0 removed
reading sources... [100%] developer/hscommon/jobprogress/qt                                                                                                                      
WARNING: autodoc: failed to import module 'qt' from module 'hscommon.jobprogress'; the following exception was raised:
No module named 'hscommon.jobprogress.qt'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                                   
generating indices... genindex py-modindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 1 warning.

The HTML pages are in build/help.
```

**Comment by glubsy** [comment]
The warning about jobprogress missing is related to commit https://github.com/arsenetar/dupeguru/commit/4c3dfe2f1f11566534d3eb8d2d54bdcc688211ab which removed jobprogress. It should not matter in this case.

**Comment by chchia** [comment]
thanks, it did run anyway.

**Comment by pataquets** [comment]
Happening also to me since last update to 4.2.0 (on #975) and @arsenetar's fix above solved it.
